version: '1'

services:
  ignition_ws:
    image: axnjr/ignition_ws
    environment:
      - DB_URL=postgresql://yakshit:-eZfWw2zQKffFmvntDaL-g@sparkdb-6147.6xw.aws-ap-southeast-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full
      - AWS_ACCESS_KEY_ID=AKIA2XD7YNLO5QLNWIUE
      - AWS_SECRET_ACCESS_KEY=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
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    